import '../../../domain/entities/provider_entity.dart';

final List<ProviderEntity> dummyProviders = [
  const ProviderEntity(
    id: '1',
    name: 'Rajesh Singh',
    serviceType: 'Luxury Car',
    location: 'Rampur',
    phoneNumber: '9876543210',
    price: 4500,
    rating: 4.5,
    totalBookings: 42,
  ),
  const ProviderEntity(
    id: '2',
    name: 'Mohan Yadav',
    serviceType: 'Jeep for Baarat',
    location: 'Kanpur',
    phoneNumber: '8765432109',
    price: 3500,
    rating: 4.2,
    totalBookings: 35,
  ),
  const ProviderEntity(
    id: '3',
    name: 'Vikram Rathore',
    serviceType: 'Luxury Car',
    location: 'Lucknow',
    phoneNumber: '7654321098',
    price: 4800,
    rating: 4.7,
    totalBookings: 58,
  ),
  const ProviderEntity(
    id: '4',
    name: 'Amit Sharma',
    serviceType: 'Wedding Bus',
    location: 'Varanasi',
    phoneNumber: '6543210987',
    price: 8000,
    rating: 4.8,
    totalBookings: 72,
  ),
  const ProviderEntity(
    id: '5',
    name: 'Rahul Verma',
    serviceType: 'Tempo Traveller',
    location: 'Allahabad',
    phoneNumber: '9432109876',
    price: 5500,
    rating: 4.3,
    totalBookings: 28,
  ),
  const ProviderEntity(
    id: '6',
    name: 'Suresh Patel',
    serviceType: 'Luxury Car',
    location: 'Gorakhpur',
    phoneNumber: '8321098765',
    price: 4200,
    rating: 4.1,
    totalBookings: 31,
  ),
  const ProviderEntity(
    id: '7',
    name: 'Anil Kumar',
    serviceType: 'Jeep for Baarat',
    location: 'Jhansi',
    phoneNumber: '9210987654',
    price: 3800,
    rating: 4.4,
    totalBookings: 45,
  ),
];
